php artisan make:model Khoa -mc
php artisan make:model BoMon -mc
php artisan make:model Nganh -mc
php artisan make:model HocPhan -mc
php artisan make:model Lop -mc
php artisan make:model Ngach -mc
php artisan make:model GiangVien -mc
php artisan make:model DinhMucBoMon -mc
php artisan make:model DinhMucGiangVien -mc
php artisan make:model QuyDoiGiamDinhMuc -mc
php artisan make:model QuyDoiGioChuan -mc
php artisan make:model QuyDoiHeSo -mc
php artisan make:model KeKhaiGiangDay -mc
php artisan make:model KeKhaiGiangDay_ChiTiet -mc
php artisan make:model KeKhaiGiamDinhMuc -mc
php artisan make:model KeKhaiHoatDongKhac -mc
php artisan make:model DuLieuThoiKhoaBieu -mc
php artisan make:model QuyDinh -mc